### ISSUE TITLE
Version 4.8 - ImportError

### ISSUE THREAD

**Issue by AlbertoJimenezDiaz** [SHTOOLS/SHTOOLS#287]
Hi Mark,

I just updated pyshtools from v.4.7.1 to v.4.8 using:

`conda update -c conda-forge pyshtools`

Now I cannot import pyshtools correctly:

```
>>> import pyshtools as pysh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/pyshtools/__init__.py", line 45, in <module>
    from . import constants
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/pyshtools/constants/__init__.py", line 43, in <module>
    from astropy.constants import codata
ImportError: cannot import name 'codata' from 'astropy.constants' (/home/alberto/anaconda3/lib/python3.7/site-packages/astropy/constants/__init__.py)
```

I have tried to uninstall and install, but I obtain the ImportError.

astropy:
```
>>> import astropy
>>> astropy.__version__
'3.2.3'
```

although via `conda list astropy` it appears:
```
# packages in environment at /home/alberto/anaconda3:
#
# Name                    Version                   Build  Channel
astropy                   4.0.1.post1              pypi_0    pypi
pytest-astropy            0.8.0              pyhd8ed1ab_0    conda-forge
pytest-astropy-header     0.1.2                      py_0    conda-forge
```

Thank you very much in advance, and sorry for the inconvenience.
Alberto

### System information
OS: Mint 18.3 sylvia
Kernel: x86_64 Linux 4.15.0-133-generic
Uptime: 1h 37m
Packages: 3032
Shell: bash 4.3.48
Resolution: 1920x1080
DE: Cinnamon 3.6.7
WM: Muffin
WM Theme: Linux Mint (Mint-X)
GTK Theme: Mint-X [GTK2/3]
Icon Theme: Mint-X
Font: Noto Sans 9
CPU: Intel Core i7-7700HQ CPU @ 3.8GHz
GPU: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
RAM: 2971MiB / 15891MiB

**Comment by AlbertoJimenezDiaz** [comment]
I forgot my System information:
```
OS: Mint 18.3 sylvia
Kernel: x86_64 Linux 4.15.0-133-generic
Uptime: 1h 37m
Packages: 3032
Shell: bash 4.3.48
Resolution: 1920x1080
DE: Cinnamon 3.6.7
WM: Muffin
WM Theme: Linux Mint (Mint-X)
GTK Theme: Mint-X [GTK2/3]
Icon Theme: Mint-X
Font: Noto Sans 9
CPU: Intel Core i7-7700HQ CPU @ 3.8GHz
GPU: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
RAM: 2971MiB / 15891MiB
```

**Comment by MarkWieczorek** [comment]
I will look at this more tomorrow, but could you do two things?

First, we had to update the conda build, so try to upgrade pyshtools, and then let me know what `conda list pyshtools` gives (it should be _1)

Second, there is a huge bug in a small project related to ipython that is causing lots of problems that are hard to debug. Try downgrading jedi from 0.18 to 0.17.2

`conda install jedi=0.17.2`

**Comment by AlbertoJimenezDiaz** [comment]
Many thanks.

I tried it, but the ImportError persists:

`conda list jedi`
```
# packages in environment at /home/alberto/anaconda3:
#
# Name                    Version                   Build  Channel
jedi                      0.17.2           py37h89c1867_1    conda-forge
```

`conda list pyshtools`
```
# packages in environment at /home/alberto/anaconda3:
#
# Name                    Version                   Build  Channel
pyshtools                 4.8              py37h6c11c6e_1    conda-forge
```

```
python3
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshtools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/pyshtools/__init__.py", line 45, in <module>
    from . import constants
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/pyshtools/constants/__init__.py", line 43, in <module>
    from astropy.constants import codata
ImportError: cannot import name 'codata' from 'astropy.constants' (/home/alberto/anaconda3/lib/python3.7/site-packages/astropy/constants/
```

**Comment by MarkWieczorek** [comment]
Could you try to uninstall and then reinstall astropy? These packages seem very suspicious
```
# packages in environment at /home/alberto/anaconda3:
#
# Name                    Version                   Build  Channel
astropy                   4.0.1.post1              pypi_0    pypi
pytest-astropy            0.8.0              pyhd8ed1ab_0    conda-forge
pytest-astropy-header     0.1.2                      py_0    conda-forge
```
For info, I have version 4.2 installed.

**Comment by MarkWieczorek** [comment]
Actually, I think that you need astropy>=4.0 I will make this explicit in the next release.

**Comment by AlbertoJimenezDiaz** [comment]
Great! That was the problem. After obtaining the ImportError, I only updated astropy using `conda update -c conda-forge astropy`, and then updated psshtools.

I have uninstalled and installed astropy=4.2, and then updated pyshtools. Now I can work with pyshtools v4.8.

```
conda list jedi
# packages in environment at /home/alberto/anaconda3:
#
# Name                    Version                   Build  Channel
jedi                      0.17.2           py37h89c1867_1    conda-forge

conda list astropy
# packages in environment at /home/alberto/anaconda3:
#
# Name                    Version                   Build  Channel
astropy                   4.2              py37h27cfd23_0  

conda list pyshtools
# packages in environment at /home/alberto/anaconda3:
#
# Name                    Version                   Build  Channel
pyshtools                 4.8              py37h6c11c6e_1    conda-forge

python3
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 21:08:20) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshtools
>>> pyshtools.__version__
'v4.8'
>>> 
```
And I just tested the installation by running an example script.

Thank you so much!
Alberto
